package pt.dlt.health.dto;

public enum Speciality {
    ALLERGY_AND_IMMUNOLOGY,
    ANESTHESIOLOGY,
    DERMATOLOGY,
    DIAGNOSTIC_RADIOLOGY,
    EMERGENCY_MEDICINE,
    FAMILY_MEDICINE,
    INTERNAL_MEDICINE,
    MEDICAL,
    NEUROLOGY,
    NUCLEAR_MEDICINE,
    OBSTETRICS_AND_GYNECOLOGY,
    OPHTHALMOLOGY,
    PATHOLOGY,
    PEDIATRICS,
    PHYSICAL_MEDICINE_AND_REHABILITATION,
    PREVENTIVE_MEDICINE,
    PSYCHIATRY,
    RADIATION_ONCOLOGY,
    SURGERY,
    UROLOGY
}